# Generated by Django 4.2.3 on 2023-07-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField()),
                ('user_email', models.TextField()),
                ('user_pass', models.TextField()),
                ('user_phone', models.TextField()),
            ],
        ),
    ]
